/* Generated from simple-icons v16.32.0 (CC0-1.0, https://simpleicons.org). Brand names and
   logos remain trademarks of their owners and are shown only to identify each service.
   Brands without a Simple Icons entry get a lettered tile in their brand colour. */

export interface Brand {
  key: string
  title: string
  /** Brand colour, #RRGGBB. */
  color: string
  /** Normalized names that map to this brand (see normalizeName). */
  aliases: string[]
  /** Has a logo; its SVG path is in brands.paths.ts, loaded on demand. */
  logo?: boolean
  /** Short text shown when there's no logo path. */
  label?: string
}

export const BRANDS: Brand[] = [
  { key: "netflix", title: "Netflix", color: "#E50914", aliases: ["netflix"], logo: true },
  { key: "youtubemusic", title: "YouTube Music", color: "#FF0000", aliases: ["youtubemusic"], logo: true },
  {
    key: "youtube",
    title: "YouTube Premium",
    color: "#FF0000",
    aliases: ["youtube", "youtubepremium", "ยูทูบ"],
    logo: true,
  },
  { key: "spotify", title: "Spotify", color: "#1ED760", aliases: ["spotify"], logo: true },
  { key: "applemusic", title: "Apple Music", color: "#FA243C", aliases: ["applemusic"], logo: true },
  { key: "appletv", title: "Apple TV+", color: "#000000", aliases: ["appletv", "appletvplus"], logo: true },
  { key: "icloud", title: "iCloud+", color: "#3693F3", aliases: ["icloud", "icloudplus"], logo: true },
  {
    key: "apple",
    title: "Apple One",
    color: "#000000",
    aliases: ["appleone", "applearcade", "applefitness"],
    logo: true,
  },
  {
    key: "googlegemini",
    title: "Google Gemini",
    color: "#8E75B2",
    aliases: ["gemini", "googlegemini", "geminiadvanced", "googleaipro"],
    logo: true,
  },
  {
    key: "googleone",
    title: "Google One",
    color: "#4285F4",
    aliases: ["googleone", "googledrive", "googlestorage"],
    logo: true,
  },
  {
    key: "claude",
    title: "Claude",
    color: "#D97757",
    aliases: ["claude", "claudepro", "claudemax", "anthropic"],
    logo: true,
  },
  { key: "perplexity", title: "Perplexity", color: "#1FB8CD", aliases: ["perplexity", "perplexitypro"], logo: true },
  { key: "cursor", title: "Cursor", color: "#000000", aliases: ["cursor"], logo: true },
  { key: "github", title: "GitHub", color: "#181717", aliases: ["github", "githubcopilot", "copilot"], logo: true },
  { key: "max", title: "Max", color: "#525252", aliases: ["max", "hbomax", "hbogo"], logo: true },
  { key: "line", title: "LINE", color: "#00C300", aliases: ["line", "linemusic", "linetv", "linemelody"], logo: true },
  { key: "notion", title: "Notion", color: "#000000", aliases: ["notion"], logo: true },
  { key: "figma", title: "Figma", color: "#F24E1E", aliases: ["figma"], logo: true },
  { key: "dropbox", title: "Dropbox", color: "#0061FF", aliases: ["dropbox"], logo: true },
  {
    key: "duolingo",
    title: "Duolingo",
    color: "#58CC02",
    aliases: ["duolingo", "duolingosuper", "duolingomax"],
    logo: true,
  },
  { key: "grammarly", title: "Grammarly", color: "#027E6F", aliases: ["grammarly"], logo: true },
  {
    key: "playstation",
    title: "PlayStation Plus",
    color: "#0070D1",
    aliases: ["playstation", "playstationplus", "psplus", "ps5"],
    logo: true,
  },
  { key: "steam", title: "Steam", color: "#000000", aliases: ["steam"], logo: true },
  {
    key: "discord",
    title: "Discord Nitro",
    color: "#5865F2",
    aliases: ["discord", "discordnitro", "nitro"],
    logo: true,
  },
  { key: "x", title: "X Premium", color: "#000000", aliases: ["x", "xpremium", "twitter", "twitterblue"], logo: true },
  { key: "twitch", title: "Twitch", color: "#9146FF", aliases: ["twitch"], logo: true },
  { key: "patreon", title: "Patreon", color: "#000000", aliases: ["patreon"], logo: true },
  { key: "medium", title: "Medium", color: "#000000", aliases: ["medium"], logo: true },
  { key: "crunchyroll", title: "Crunchyroll", color: "#FF5E00", aliases: ["crunchyroll"], logo: true },
  { key: "bilibili", title: "Bilibili", color: "#00A1D6", aliases: ["bilibili"], logo: true },
  { key: "tidal", title: "TIDAL", color: "#000000", aliases: ["tidal"], logo: true },
  { key: "deezer", title: "Deezer", color: "#A238FF", aliases: ["deezer"], logo: true },
  { key: "soundcloud", title: "SoundCloud", color: "#FF5500", aliases: ["soundcloud", "soundcloudgo"], logo: true },
  { key: "audible", title: "Audible", color: "#F8991C", aliases: ["audible"], logo: true },
  { key: "zoom", title: "Zoom", color: "#0B5CFF", aliases: ["zoom", "zoompro", "zoomworkplace"], logo: true },
  { key: "1password", title: "1Password", color: "#145FE4", aliases: ["1password"], logo: true },
  { key: "bitwarden", title: "Bitwarden", color: "#175DDC", aliases: ["bitwarden"], logo: true },
  { key: "nordvpn", title: "NordVPN", color: "#4687FF", aliases: ["nordvpn"], logo: true },
  { key: "expressvpn", title: "ExpressVPN", color: "#DA3940", aliases: ["expressvpn"], logo: true },
  {
    key: "protonvpn",
    title: "Proton VPN",
    color: "#66DEB1",
    aliases: ["protonvpn", "proton", "protonmail"],
    logo: true,
  },
  { key: "surfshark", title: "Surfshark", color: "#1EBFBF", aliases: ["surfshark"], logo: true },
  { key: "evernote", title: "Evernote", color: "#00A82D", aliases: ["evernote"], logo: true },
  { key: "todoist", title: "Todoist", color: "#E44332", aliases: ["todoist"], logo: true },
  { key: "strava", title: "Strava", color: "#FC4C02", aliases: ["strava"], logo: true },
  { key: "headspace", title: "Headspace", color: "#F47D31", aliases: ["headspace"], logo: true },
  { key: "tinder", title: "Tinder", color: "#FF6B6B", aliases: ["tinder", "tindergold", "tinderplus"], logo: true },
  {
    key: "disneyplus",
    title: "Disney+ Hotstar",
    color: "#113CCF",
    aliases: ["disney", "disneyplus", "disneyhotstar", "disneyplushotstar", "hotstar"],
    label: "D+",
  },
  {
    key: "chatgpt",
    title: "ChatGPT",
    color: "#10A37F",
    aliases: ["chatgpt", "chatgptplus", "chatgptpro", "openai"],
    label: "AI",
  },
  {
    key: "primevideo",
    title: "Prime Video",
    color: "#1A98FF",
    aliases: ["primevideo", "amazonprime", "amazonprimevideo", "prime"],
    label: "P",
  },
  { key: "canva", title: "Canva", color: "#00C4CC", aliases: ["canva", "canvapro"], label: "C" },
  {
    key: "microsoft365",
    title: "Microsoft 365",
    color: "#D83B01",
    aliases: ["microsoft365", "office365", "m365", "onedrive"],
    label: "M",
  },
  {
    key: "adobe",
    title: "Adobe Creative Cloud",
    color: "#DA1F26",
    aliases: ["adobe", "adobecc", "adobecreativecloud", "photoshop", "lightroom"],
    label: "Ad",
  },
  { key: "viu", title: "Viu", color: "#F7B500", aliases: ["viu"], label: "viu" },
  { key: "wetv", title: "WeTV", color: "#FF6A00", aliases: ["wetv"], label: "We" },
  { key: "iqiyi", title: "iQIYI", color: "#00BE06", aliases: ["iqiyi", "iqiyivip"], label: "iQ" },
  { key: "trueid", title: "TrueID", color: "#E4032E", aliases: ["trueid", "trueidplus"], label: "T" },
  { key: "monomax", title: "MONOMAX", color: "#1C1C1C", aliases: ["monomax", "mono29"], label: "M" },
  {
    key: "ais",
    title: "AIS",
    color: "#7AB800",
    aliases: ["ais", "aisfibre", "aisรายเดือน", "aispostpaid", "ais5g", "aisplay"],
    label: "AIS",
  },
  {
    key: "truemove",
    title: "True",
    color: "#E4032E",
    aliases: ["true", "trueonline", "trueรายเดือน", "truepostpaid", "truemove", "truemoveh", "true5g"],
    label: "true",
  },
  { key: "dtac", title: "dtac", color: "#00A5E3", aliases: ["dtac", "dtacรายเดือน", "dtacpostpaid"], label: "dtac" },
  { key: "3bb", title: "3BB", color: "#FF6A13", aliases: ["3bb", "3bbfiber", "3bbgiga"], label: "3BB" },
  { key: "nt", title: "NT", color: "#F7A600", aliases: ["nt", "ntbroadband", "ntfiber", "tot"], label: "NT" },
  { key: "joox", title: "JOOX", color: "#00C16A", aliases: ["joox", "jooxvip"], label: "J" },
  { key: "fitnessfirst", title: "Fitness First", color: "#E2231A", aliases: ["fitnessfirst"], label: "FF" },
  { key: "jetts", title: "Jetts Fitness", color: "#F26522", aliases: ["jetts", "jettsfitness"], label: "J" },
  { key: "xbox", title: "Xbox Game Pass", color: "#107C10", aliases: ["xbox", "xboxgamepass", "gamepass"], label: "X" },
  {
    key: "nintendo",
    title: "Nintendo Switch Online",
    color: "#E60012",
    aliases: ["nintendo", "nintendoswitchonline", "switchonline"],
    label: "N",
  },
  {
    key: "cloudflare",
    title: "Cloudflare",
    color: "#F38020",
    aliases: ["cloudflare", "cloudflareregistrar", "cloudflaredomain"],
    logo: true,
  },
  { key: "namecheap", title: "Namecheap", color: "#DE3723", aliases: ["namecheap"], logo: true },
  { key: "godaddy", title: "GoDaddy", color: "#1BDBDB", aliases: ["godaddy"], logo: true },
  { key: "porkbun", title: "Porkbun", color: "#EF7878", aliases: ["porkbun"], logo: true },
  { key: "hostinger", title: "Hostinger", color: "#673DE6", aliases: ["hostinger"], logo: true },
  { key: "wix", title: "Wix", color: "#0C6EFC", aliases: ["wix", "wixpremium"], logo: true },
  { key: "vercel", title: "Vercel", color: "#000000", aliases: ["vercel", "vercelpro"], logo: true },
  { key: "netlify", title: "Netlify", color: "#00C7B7", aliases: ["netlify"], logo: true },
  { key: "digitalocean", title: "DigitalOcean", color: "#0080FF", aliases: ["digitalocean"], logo: true },
  { key: "googlecloud", title: "Google Cloud", color: "#4285F4", aliases: ["googlecloud", "gcp"], logo: true },
  { key: "supabase", title: "Supabase", color: "#3FCF8E", aliases: ["supabase", "supabasepro"], logo: true },
  { key: "aws", title: "AWS", color: "#FF9900", aliases: ["aws", "amazonwebservices"], label: "aws" },
  {
    key: "googleworkspace",
    title: "Google Workspace",
    color: "#4285F4",
    aliases: ["googleworkspace", "gsuite"],
    label: "G",
  },
]
